sonar.organization=developer-310
sonar.projectKey=developer-310_azuredvopspractice
sonar.projectName=azuredvopspractice

# Path to the source directories
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Language configuration
sonar.language=java
sonar.sourceEncoding=UTF-8